

console.log("methods");
const startx = Date.now();
let strw = "Lorem, Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam"
let revx = strw.split('');
console.log(revx.reverse().join(''));
const endx = Date.now();
console.log(`Execution time: ${endx - startx} ms`);


console.log("loop");
const start = Date.now();
let str = "Lorem, Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam  ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam";
let len = str.length - 1;
rev='';
for (i = len; i >= 0; i--){
    rev = rev + str[i];
}
console.log(rev); 
const end = Date.now(); 
console.log(`Execution time: ${end - start} ms`);


console.log("loop"); 
const start1 = Date.now();
let str1 = "Lorem, Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam";
let len1 = str1.length - 1;
rev1='';
for (i = len1; i >= 0; i--){
    rev1 = rev1 + str1[i];
}
console.log(rev1); 
const end1 = Date.now(); 
console.log(`Execution time: ${end1 - start1} ms`);



console.log("methods");
const startx1 = Date.now();
let strw1 = "Lorem, Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam  ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam consequuntur sunt molestias eum incidunt molestiae velit! Eum quam eveniet expedita, aliquid voluptas velit quis optio impedit, nam ut provident. Cumque, consequuntur dolorum quidem, id praesentium odio voluptate ullam molestiae provident cum consequatur. Totam sed fuga, repudiandae aliquid excepturi dolorem consectetur qui, ipsam vitae magni porro harum nulla quibusdam? Animi placeat nemo quibusdam, dolore aliquam eius a et, quia recusandae labore corporis, distinctio odit itaque voluptatum autem vel aut fuga neque ad laudantium tempora delectus? Et, architecto nobis numquam neque officia deserunt porro magni repellat delectus est quaerat quod ut nam";
let revx1 = strw1.split('');
console.log(revx1.reverse().join(''));
const endx1 = Date.now();
console.log(`Execution time: ${endx1 - startx1} ms`);


